// SPDX-License-Identifier: LGPL-3.0-or-later

namespace LobotomyCorporation.Mods.ConfigurationManager.Integration.Emit
{
    /// <summary>
    /// Author-visible API surface that <c>Config.Bind(...)</c> call sites compile against:
    /// the <c>Config</c> partial static class with overloads, the <c>IConfigValue&lt;T&gt;</c> and
    /// <c>ConfigValue&lt;T&gt;</c> pair, the <c>ConfigManagerMod</c> marker attribute, and the
    /// <c>ConfigFallback</c> enum. Emitted as post-init source so the author's code compiles
    /// before the binding scanner runs.
    /// </summary>
    internal static class ApiSurfaceEmitter
    {
        public const string Source =
            @"// <auto-generated/>
// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma warning disable

using System;
using System.Collections.Generic;

namespace LobotomyCorporation.Mods.ConfigurationManager
{
    /// <summary>
    /// Read-only handle to a config value. Returned by <c>Config.Bind</c>. The underlying store is
    /// either ConfigurationManager (if installed) or an in-memory fallback.
    /// </summary>
    internal interface IConfigValue<T>
    {
        T Value { get; set; }
        T DefaultValue { get; }
        string Section { get; }
        string Key { get; }
        event EventHandler ValueChanged;
    }

    internal sealed class ConfigValue<T> : IConfigValue<T>
    {
        private T _value;
        private readonly T _defaultValue;

        internal ConfigValue(string section, string key, T defaultValue)
        {
            Section = section;
            Key = key;
            _defaultValue = defaultValue;
            _value = defaultValue;
        }

        public T Value
        {
            get { return _value; }
            set
            {
                if (Equals(_value, value)) { return; }
                _value = value;
                var handler = ValueChanged;
                if (handler != null) { handler(this, EventArgs.Empty); }
            }
        }

        public T DefaultValue { get { return _defaultValue; } }
        public string Section { get; private set; }
        public string Key { get; private set; }
        public event EventHandler ValueChanged;
    }

    /// <summary>
    /// Strategy for what happens when ConfigurationManager is not installed at runtime.
    /// </summary>
    internal enum ConfigFallback
    {
        /// <summary>Bindings live in a non-persisted in-memory store. Values are lost on mod unload.</summary>
        InMemory = 0,

        /// <summary>Reserved for a future release — not implemented in v1. Treated as <c>InMemory</c> at runtime.</summary>
        FileBacked = 1,
    }

    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
    internal sealed class ConfigManagerModAttribute : Attribute
    {
        public string ModId { get; set; }
        public string ModName { get; set; }
        public string ModVersion { get; set; }
        public ConfigFallback Fallback { get; set; }
    }

    internal static partial class Config
    {
        internal sealed class BindingDescriptor
        {
            public string Section;
            public string Key;
            public Type ValueType;
            public object DefaultValue;
            public object ValueHandle;
            public string Description;
            public object MinValue;
            public object MaxValue;
            public object CmAttributes;
            public Action<object> ApplyFromCm;
            public Action<object> PushToCm;
        }

        internal static readonly List<BindingDescriptor> _bindings = new List<BindingDescriptor>();

        public static IConfigValue<T> Bind<T>(
            string section,
            string key,
            T defaultValue,
            string description = null,
            T minValue = default(T),
            T maxValue = default(T),
            int? order = null,
            bool? isAdvanced = null,
            string category = null,
            string dispName = null,
            bool? browsable = null,
            bool? readOnly = null,
            bool? hideDefaultButton = null,
            bool? hideSettingName = null,
            bool? showRangeAsPercent = null,
            bool? useIntegerSlider = null
        )
        {
            var value = new ConfigValue<T>(section, key, defaultValue);

            var hasRange = !Equals(minValue, default(T)) || !Equals(maxValue, default(T));

            var cmAttrs = new ConfigurationManagerAttributes
            {
                Order = order,
                IsAdvanced = isAdvanced,
                Category = category,
                DispName = dispName,
                Browsable = browsable,
                ReadOnly = readOnly,
                HideDefaultButton = hideDefaultButton,
                HideSettingName = hideSettingName,
                ShowRangeAsPercent = showRangeAsPercent,
                UseIntegerSlider = useIntegerSlider,
                Description = description,
            };

            _bindings.Add(new BindingDescriptor
            {
                Section = section,
                Key = key,
                ValueType = typeof(T),
                DefaultValue = defaultValue,
                ValueHandle = value,
                Description = description,
                MinValue = hasRange ? (object)minValue : null,
                MaxValue = hasRange ? (object)maxValue : null,
                CmAttributes = cmAttrs,
                ApplyFromCm = boxed => { value.Value = (T)boxed; },
                PushToCm = null,
            });

            return value;
        }
    }
}
#pragma warning restore
";
    }
}
