// SPDX-License-Identifier: LGPL-3.0-or-later

namespace LobotomyCorporation.Mods.ConfigurationManager.Integration.Emit
{
    /// <summary>
    /// Copy of <c>ConfigurationManagerAttributes</c> emitted into the mod's own assembly.
    /// CM reads these via simple-name reflection and <c>GetProperties()</c>, so the emitted
    /// type matches upstream's property names exactly and uses <c>Nullable&lt;T&gt;</c> for
    /// every optional hint so unset values are skipped by CM's <c>if (val != null)</c> check.
    /// </summary>
    internal static class CmAttributesEmitter
    {
        public const string Source =
            @"// <auto-generated/>
// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma warning disable

namespace LobotomyCorporation.Mods.ConfigurationManager
{
    /// <summary>
    /// Per-mod copy of <c>ConfigurationManagerAttributes</c>. ConfigurationManager discovers this
    /// by simple type name, not by assembly identity, so each mod ships its own identical class.
    /// </summary>
    internal sealed class ConfigurationManagerAttributes
    {
        public bool? ShowRangeAsPercent { get; set; }
        public bool? UseIntegerSlider { get; set; }
        public bool? Browsable { get; set; }
        public string Category { get; set; }
        public object DefaultValue { get; set; }
        public bool? HideDefaultButton { get; set; }
        public bool? HideSettingName { get; set; }
        public string Description { get; set; }
        public string DispName { get; set; }
        public int? Order { get; set; }
        public bool? ReadOnly { get; set; }
        public bool? IsAdvanced { get; set; }
    }
}
#pragma warning restore
";
    }
}
