// SPDX-License-Identifier: LGPL-3.0-or-later

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace LobotomyCorporation.Mods.ConfigurationManager.Integration.Emit
{
    /// <summary>
    /// Emits the second partial of <c>Config</c> containing <c>RegisterAll()</c> plus the reflective
    /// interop that binds the mod's <c>ConfigValue&lt;T&gt;</c> handles to ConfigurationManager's
    /// <c>LmmConfigEntry&lt;T&gt;</c> at runtime. Hardcodes the set of containing types to force
    /// their static constructors so field initializers that call <c>Config.Bind</c> are guaranteed
    /// to have run before registration begins.
    /// </summary>
    internal static class RegistrationEmitter
    {
        public static string Emit(
            ImmutableArray<BindingModel> bindings,
            ModAttributeModel? modAttribute
        )
        {
            var sb = new StringBuilder();
            _ = sb.AppendLine("// <auto-generated/>");
            _ = sb.AppendLine("// SPDX-License-Identifier: LGPL-3.0-or-later");
            _ = sb.AppendLine("#pragma warning disable");
            _ = sb.AppendLine();
            _ = sb.AppendLine("using System;");
            _ = sb.AppendLine("using System.Collections.Generic;");
            _ = sb.AppendLine("using System.Reflection;");
            _ = sb.AppendLine();
            _ = sb.AppendLine("namespace LobotomyCorporation.Mods.ConfigurationManager");
            _ = sb.AppendLine("{");
            _ = sb.AppendLine("    internal static partial class Config");
            _ = sb.AppendLine("    {");
            EmitModIdentity(sb, modAttribute);
            EmitContainingTypeList(sb, bindings);
            EmitRegisterAll(sb);
            EmitCmInteropHelpers(sb);
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine("}");
            _ = sb.AppendLine("#pragma warning restore");
            return sb.ToString();
        }

        private static void EmitModIdentity(StringBuilder sb, ModAttributeModel? modAttribute)
        {
            var modId = modAttribute?.ModId ?? "unknown.mod";
            var modName = modAttribute?.ModName ?? "Unknown Mod";
            var modVersion = modAttribute?.ModVersion ?? string.Empty;
            _ = sb.AppendLine("        private const string _modId = " + Literal(modId) + ";");
            _ = sb.AppendLine("        private const string _modName = " + Literal(modName) + ";");
            _ = sb.AppendLine(
                "        private const string _modVersion = " + Literal(modVersion) + ";"
            );
            _ = sb.AppendLine();
        }

        private static void EmitContainingTypeList(
            StringBuilder sb,
            ImmutableArray<BindingModel> bindings
        )
        {
            var seen = new HashSet<string>(System.StringComparer.Ordinal);
            _ = sb.AppendLine(
                "        private static readonly Type[] _containingTypes = new Type[]"
            );
            _ = sb.AppendLine("        {");
            foreach (var binding in bindings)
            {
                if (!seen.Add(binding.ContainingTypeFullName))
                {
                    continue;
                }

                _ = sb.AppendLine("            typeof(" + binding.ContainingTypeFullName + "),");
            }

            _ = sb.AppendLine("        };");
            _ = sb.AppendLine();
        }

        private static void EmitRegisterAll(StringBuilder sb)
        {
            _ = sb.AppendLine("        private static bool _registered;");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "        /// <summary>Registers every Config.Bind declaration with ConfigurationManager if it is installed."
            );
            _ = sb.AppendLine(
                "        /// Safe to call more than once; subsequent calls are no-ops. If ConfigurationManager is absent,"
            );
            _ = sb.AppendLine(
                "        /// bindings fall back to an in-memory store and RegisterAll returns without throwing.</summary>"
            );
            _ = sb.AppendLine("        public static void RegisterAll()");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            if (_registered) { return; }");
            _ = sb.AppendLine("            _registered = true;");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            foreach (var t in _containingTypes)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                try");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(t.TypeHandle);"
            );
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("                catch (Exception ex)");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    TryLog(\"[ConfigurationManager.Integration] Failed to initialize \" + t + \": \" + ex);"
            );
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var lmmRegType = ResolveCmType(\"ConfigurationManager.Config.LmmConfigRegistration\");"
            );
            _ = sb.AppendLine("            if (lmmRegType == null) { return; }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var descType = ResolveCmType(\"ConfigurationManager.Config.LmmConfigDescription\");"
            );
            _ = sb.AppendLine(
                "            var acceptableValueType = ResolveCmType(\"ConfigurationManager.Config.IAcceptableValue\");"
            );
            _ = sb.AppendLine(
                "            var rangeOpenGeneric = ResolveCmType(\"ConfigurationManager.Config.AcceptableValueRange`1\");"
            );
            _ = sb.AppendLine("            if (descType == null || acceptableValueType == null)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                TryLog(\"[ConfigurationManager.Integration] ConfigurationManager version mismatch: required types missing. Falling back to in-memory.\");"
            );
            _ = sb.AppendLine("                return;");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var descCtor = FindDescriptionConstructor(descType, acceptableValueType);"
            );
            _ = sb.AppendLine(
                "            var registerOpen = FindRegisterMethod(lmmRegType, descType);"
            );
            _ = sb.AppendLine("            if (descCtor == null || registerOpen == null)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                TryLog(\"[ConfigurationManager.Integration] ConfigurationManager version mismatch: required members missing. Falling back to in-memory.\");"
            );
            _ = sb.AppendLine("                return;");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            foreach (var binding in _bindings)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                try");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    RegisterBinding(binding, descType, acceptableValueType, rangeOpenGeneric, descCtor, registerOpen);"
            );
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("                catch (Exception ex)");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    TryLog(\"[ConfigurationManager.Integration] Failed to register \" + binding.Section + \".\" + binding.Key + \": \" + ex);"
            );
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
        }

        private static void EmitCmInteropHelpers(StringBuilder sb)
        {
            _ = sb.AppendLine("        private static Type ResolveCmType(string fullName)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine(
                "            var t = Type.GetType(fullName + \", ConfigurationManager\");"
            );
            _ = sb.AppendLine("            if (t != null) { return t; }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())"
            );
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                try");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    if (assembly.GetName().Name != \"ConfigurationManager\") { continue; }"
            );
            _ = sb.AppendLine("                    var candidate = assembly.GetType(fullName);");
            _ = sb.AppendLine("                    if (candidate != null) { return candidate; }");
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("                catch { }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("            return null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "        private static ConstructorInfo FindDescriptionConstructor(Type descType, Type acceptableValueType)"
            );
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            foreach (var ctor in descType.GetConstructors())");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                var p = ctor.GetParameters();");
            _ = sb.AppendLine(
                "                if (p.Length == 3 && p[0].ParameterType == typeof(string) && p[1].ParameterType == acceptableValueType && p[2].ParameterType == typeof(object[]))"
            );
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine("                    return ctor;");
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("            return null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "        private static MethodInfo FindRegisterMethod(Type lmmRegType, Type descType)"
            );
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine(
                "            foreach (var m in lmmRegType.GetMethods(BindingFlags.Public | BindingFlags.Static))"
            );
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                if (m.Name != \"Register\" || !m.IsGenericMethodDefinition) { continue; }"
            );
            _ = sb.AppendLine("                var p = m.GetParameters();");
            _ = sb.AppendLine(
                "                if (p.Length == 7 && p[5].ParameterType == descType) { return m; }"
            );
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("            return null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "        private static void RegisterBinding(BindingDescriptor binding, Type descType, Type acceptableValueType, Type rangeOpenGeneric, ConstructorInfo descCtor, MethodInfo registerOpen)"
            );
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            object acceptableValue = null;");
            _ = sb.AppendLine(
                "            if (binding.MinValue != null && binding.MaxValue != null && rangeOpenGeneric != null)"
            );
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                var closedRange = rangeOpenGeneric.MakeGenericType(binding.ValueType);"
            );
            _ = sb.AppendLine(
                "                acceptableValue = Activator.CreateInstance(closedRange, binding.MinValue, binding.MaxValue);"
            );
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var description = descCtor.Invoke(new object[] { binding.Description ?? string.Empty, acceptableValue, new object[] { binding.CmAttributes } });"
            );
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var registerClosed = registerOpen.MakeGenericMethod(binding.ValueType);"
            );
            _ = sb.AppendLine(
                "            var entry = registerClosed.Invoke(null, new object[] { _modId, _modName, binding.Section, binding.Key, binding.DefaultValue, description, _modVersion });"
            );
            _ = sb.AppendLine("            if (entry == null) { return; }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            var entryType = entry.GetType();");
            _ = sb.AppendLine(
                "            var valueProperty = entryType.GetProperty(\"Value\", BindingFlags.Instance | BindingFlags.Public);"
            );
            _ = sb.AppendLine(
                "            var settingChangedEvent = entryType.GetEvent(\"SettingChanged\", BindingFlags.Instance | BindingFlags.Public | BindingFlags.FlattenHierarchy);"
            );
            _ = sb.AppendLine(
                "            if (valueProperty == null || settingChangedEvent == null) { return; }"
            );
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            // Seed the value handle with whatever CM loaded (may have been populated from the persisted config file)."
            );
            _ = sb.AppendLine(
                "            binding.ApplyFromCm(valueProperty.GetValue(entry, null));"
            );
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var sink = new BindingSink(binding, entry, valueProperty);"
            );
            _ = sb.AppendLine("            binding.PushToCm = sink.PushToCm;");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            var handlerType = settingChangedEvent.EventHandlerType;"
            );
            _ = sb.AppendLine(
                "            var handlerMethod = typeof(BindingSink).GetMethod(\"OnCmChanged\", BindingFlags.Instance | BindingFlags.Public);"
            );
            _ = sb.AppendLine(
                "            var handler = Delegate.CreateDelegate(handlerType, sink, handlerMethod);"
            );
            _ = sb.AppendLine("            settingChangedEvent.AddEventHandler(entry, handler);");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            // Wire the local-to-CM direction: subscribing on a boxed IConfigValue<T> means we"
            );
            _ = sb.AppendLine(
                "            // reflect onto its ValueChanged event since T is only known at runtime here."
            );
            _ = sb.AppendLine("            var valueHandleType = binding.ValueHandle.GetType();");
            _ = sb.AppendLine(
                "            var valueChangedEvent = valueHandleType.GetEvent(\"ValueChanged\");"
            );
            _ = sb.AppendLine("            if (valueChangedEvent != null)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                var localMethod = typeof(BindingSink).GetMethod(\"OnLocalChanged\", BindingFlags.Instance | BindingFlags.Public);"
            );
            _ = sb.AppendLine(
                "                var localHandler = Delegate.CreateDelegate(valueChangedEvent.EventHandlerType, sink, localMethod);"
            );
            _ = sb.AppendLine(
                "                valueChangedEvent.AddEventHandler(binding.ValueHandle, localHandler);"
            );
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("        private static void TryLog(string message)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            try { UnityEngine.Debug.Log(message); }");
            _ = sb.AppendLine("            catch { }");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("        internal sealed class BindingSink");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            private readonly BindingDescriptor _binding;");
            _ = sb.AppendLine("            private readonly object _cmEntry;");
            _ = sb.AppendLine("            private readonly PropertyInfo _valueProperty;");
            _ = sb.AppendLine("            [ThreadStatic] private static bool _suppress;");
            _ = sb.AppendLine();
            _ = sb.AppendLine(
                "            public BindingSink(BindingDescriptor binding, object cmEntry, PropertyInfo valueProperty)"
            );
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                _binding = binding;");
            _ = sb.AppendLine("                _cmEntry = cmEntry;");
            _ = sb.AppendLine("                _valueProperty = valueProperty;");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            public void OnCmChanged(object sender, EventArgs e)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                if (_suppress) { return; }");
            _ = sb.AppendLine("                _suppress = true;");
            _ = sb.AppendLine("                try");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine(
                "                    _binding.ApplyFromCm(_valueProperty.GetValue(_cmEntry, null));"
            );
            _ = sb.AppendLine("                }");
            _ = sb.AppendLine("                finally { _suppress = false; }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            public void OnLocalChanged(object sender, EventArgs e)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                if (_suppress) { return; }");
            _ = sb.AppendLine("                _suppress = true;");
            _ = sb.AppendLine(
                "                try { PushToCm(_valueProperty.GetValue(_cmEntry, null)); }"
            );
            _ = sb.AppendLine("                finally { _suppress = false; }");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("            public void PushToCm(object newValue)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine(
                "                // Read the up-to-date value off the local handle reflectively; _cmEntry.Value is the push target."
            );
            _ = sb.AppendLine("                var handleType = _binding.ValueHandle.GetType();");
            _ = sb.AppendLine(
                "                var handleValue = handleType.GetProperty(\"Value\").GetValue(_binding.ValueHandle, null);"
            );
            _ = sb.AppendLine(
                "                _valueProperty.SetValue(_cmEntry, handleValue, null);"
            );
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("        }");
        }

        private static string Literal(string value)
        {
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }
    }
}
