//HintName: ConfigurationManager.CmAttributes.g.cs
// <auto-generated/>
// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma warning disable

namespace LobotomyCorporation.Mods.ConfigurationManager
{
    /// <summary>
    /// Per-mod copy of <c>ConfigurationManagerAttributes</c>. ConfigurationManager discovers this
    /// by simple type name, not by assembly identity, so each mod ships its own identical class.
    /// </summary>
    internal sealed class ConfigurationManagerAttributes
    {
        public bool? ShowRangeAsPercent { get; set; }
        public bool? UseIntegerSlider { get; set; }
        public bool? Browsable { get; set; }
        public string Category { get; set; }
        public object DefaultValue { get; set; }
        public bool? HideDefaultButton { get; set; }
        public bool? HideSettingName { get; set; }
        public string Description { get; set; }
        public string DispName { get; set; }
        public int? Order { get; set; }
        public bool? ReadOnly { get; set; }
        public bool? IsAdvanced { get; set; }
    }
}
#pragma warning restore
