//HintName: ConfigurationManager.Registration.g.cs
// <auto-generated/>
// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma warning disable

using System;
using System.Collections.Generic;
using System.Reflection;

namespace LobotomyCorporation.Mods.ConfigurationManager
{
    internal static partial class Config
    {
        private const string _modId = "com.test.mod";
        private const string _modName = "Test Mod";
        private const string _modVersion = "1.0.0";

        private static readonly Type[] _containingTypes = new Type[]
        {
            typeof(global::TestMod.MyConfig),
        };

        private static bool _registered;

        /// <summary>Registers every Config.Bind declaration with ConfigurationManager if it is installed.
        /// Safe to call more than once; subsequent calls are no-ops. If ConfigurationManager is absent,
        /// bindings fall back to an in-memory store and RegisterAll returns without throwing.</summary>
        public static void RegisterAll()
        {
            if (_registered) { return; }
            _registered = true;

            foreach (var t in _containingTypes)
            {
                try
                {
                    System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(t.TypeHandle);
                }
                catch (Exception ex)
                {
                    TryLog("[ConfigurationManager.Integration] Failed to initialize " + t + ": " + ex);
                }
            }

            var lmmRegType = ResolveCmType("ConfigurationManager.Config.LmmConfigRegistration");
            if (lmmRegType == null) { return; }

            var descType = ResolveCmType("ConfigurationManager.Config.LmmConfigDescription");
            var acceptableValueType = ResolveCmType("ConfigurationManager.Config.IAcceptableValue");
            var rangeOpenGeneric = ResolveCmType("ConfigurationManager.Config.AcceptableValueRange`1");
            if (descType == null || acceptableValueType == null)
            {
                TryLog("[ConfigurationManager.Integration] ConfigurationManager version mismatch: required types missing. Falling back to in-memory.");
                return;
            }

            var descCtor = FindDescriptionConstructor(descType, acceptableValueType);
            var registerOpen = FindRegisterMethod(lmmRegType, descType);
            if (descCtor == null || registerOpen == null)
            {
                TryLog("[ConfigurationManager.Integration] ConfigurationManager version mismatch: required members missing. Falling back to in-memory.");
                return;
            }

            foreach (var binding in _bindings)
            {
                try
                {
                    RegisterBinding(binding, descType, acceptableValueType, rangeOpenGeneric, descCtor, registerOpen);
                }
                catch (Exception ex)
                {
                    TryLog("[ConfigurationManager.Integration] Failed to register " + binding.Section + "." + binding.Key + ": " + ex);
                }
            }
        }

        private static Type ResolveCmType(string fullName)
        {
            var t = Type.GetType(fullName + ", ConfigurationManager");
            if (t != null) { return t; }

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    if (assembly.GetName().Name != "ConfigurationManager") { continue; }
                    var candidate = assembly.GetType(fullName);
                    if (candidate != null) { return candidate; }
                }
                catch { }
            }
            return null;
        }

        private static ConstructorInfo FindDescriptionConstructor(Type descType, Type acceptableValueType)
        {
            foreach (var ctor in descType.GetConstructors())
            {
                var p = ctor.GetParameters();
                if (p.Length == 3 && p[0].ParameterType == typeof(string) && p[1].ParameterType == acceptableValueType && p[2].ParameterType == typeof(object[]))
                {
                    return ctor;
                }
            }
            return null;
        }

        private static MethodInfo FindRegisterMethod(Type lmmRegType, Type descType)
        {
            foreach (var m in lmmRegType.GetMethods(BindingFlags.Public | BindingFlags.Static))
            {
                if (m.Name != "Register" || !m.IsGenericMethodDefinition) { continue; }
                var p = m.GetParameters();
                if (p.Length == 7 && p[5].ParameterType == descType) { return m; }
            }
            return null;
        }

        private static void RegisterBinding(BindingDescriptor binding, Type descType, Type acceptableValueType, Type rangeOpenGeneric, ConstructorInfo descCtor, MethodInfo registerOpen)
        {
            object acceptableValue = null;
            if (binding.MinValue != null && binding.MaxValue != null && rangeOpenGeneric != null)
            {
                var closedRange = rangeOpenGeneric.MakeGenericType(binding.ValueType);
                acceptableValue = Activator.CreateInstance(closedRange, binding.MinValue, binding.MaxValue);
            }

            var description = descCtor.Invoke(new object[] { binding.Description ?? string.Empty, acceptableValue, new object[] { binding.CmAttributes } });

            var registerClosed = registerOpen.MakeGenericMethod(binding.ValueType);
            var entry = registerClosed.Invoke(null, new object[] { _modId, _modName, binding.Section, binding.Key, binding.DefaultValue, description, _modVersion });
            if (entry == null) { return; }

            var entryType = entry.GetType();
            var valueProperty = entryType.GetProperty("Value", BindingFlags.Instance | BindingFlags.Public);
            var settingChangedEvent = entryType.GetEvent("SettingChanged", BindingFlags.Instance | BindingFlags.Public | BindingFlags.FlattenHierarchy);
            if (valueProperty == null || settingChangedEvent == null) { return; }

            // Seed the value handle with whatever CM loaded (may have been populated from the persisted config file).
            binding.ApplyFromCm(valueProperty.GetValue(entry, null));

            var sink = new BindingSink(binding, entry, valueProperty);
            binding.PushToCm = sink.PushToCm;

            var handlerType = settingChangedEvent.EventHandlerType;
            var handlerMethod = typeof(BindingSink).GetMethod("OnCmChanged", BindingFlags.Instance | BindingFlags.Public);
            var handler = Delegate.CreateDelegate(handlerType, sink, handlerMethod);
            settingChangedEvent.AddEventHandler(entry, handler);

            // Wire the local-to-CM direction: subscribing on a boxed IConfigValue<T> means we
            // reflect onto its ValueChanged event since T is only known at runtime here.
            var valueHandleType = binding.ValueHandle.GetType();
            var valueChangedEvent = valueHandleType.GetEvent("ValueChanged");
            if (valueChangedEvent != null)
            {
                var localMethod = typeof(BindingSink).GetMethod("OnLocalChanged", BindingFlags.Instance | BindingFlags.Public);
                var localHandler = Delegate.CreateDelegate(valueChangedEvent.EventHandlerType, sink, localMethod);
                valueChangedEvent.AddEventHandler(binding.ValueHandle, localHandler);
            }
        }

        private static void TryLog(string message)
        {
            try { UnityEngine.Debug.Log(message); }
            catch { }
        }

        internal sealed class BindingSink
        {
            private readonly BindingDescriptor _binding;
            private readonly object _cmEntry;
            private readonly PropertyInfo _valueProperty;
            [ThreadStatic] private static bool _suppress;

            public BindingSink(BindingDescriptor binding, object cmEntry, PropertyInfo valueProperty)
            {
                _binding = binding;
                _cmEntry = cmEntry;
                _valueProperty = valueProperty;
            }

            public void OnCmChanged(object sender, EventArgs e)
            {
                if (_suppress) { return; }
                _suppress = true;
                try
                {
                    _binding.ApplyFromCm(_valueProperty.GetValue(_cmEntry, null));
                }
                finally { _suppress = false; }
            }

            public void OnLocalChanged(object sender, EventArgs e)
            {
                if (_suppress) { return; }
                _suppress = true;
                try { PushToCm(_valueProperty.GetValue(_cmEntry, null)); }
                finally { _suppress = false; }
            }

            public void PushToCm(object newValue)
            {
                // Read the up-to-date value off the local handle reflectively; _cmEntry.Value is the push target.
                var handleType = _binding.ValueHandle.GetType();
                var handleValue = handleType.GetProperty("Value").GetValue(_binding.ValueHandle, null);
                _valueProperty.SetValue(_cmEntry, handleValue, null);
            }
        }
    }
}
#pragma warning restore
